2016-12-16 10:20:02,553 - knowledge_logger - main.py-handle-api- : 'domain_ids' 

2016-12-16 10:20:02,648 - knowledge_logger - main.py : Traceback (most recent call last):
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 203, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 307, in handle_admin
    return controller.process_admin_request(request, db)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\admincontroller.py", line 116, in process_admin_request
    db, request_frame, session_user)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\admincontroller.py", line 514, in get_reassign_user_account_form_data
    units = get_units(db)
  File "D:\Bogi\Project\Compfie\Src-server\server\database\technomaster.py", line 1608, in get_units
    return return_units(result)
  File "D:\Bogi\Project\Compfie\Src-server\server\database\technomaster.py", line 1620, in return_units
    domain_ids = [int(x) for x in unit["domain_ids"].split(',') if x != '']
KeyError: 'domain_ids'
 

2016-12-16 10:27:06,187 - knowledge_logger - main.py-parse-request : null is not allowed 

2016-12-16 10:27:06,190 - knowledge_logger - main.py : Traceback (most recent call last):
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 155, in _parse_request
    data
  File "D:\Bogi\Project\Compfie\Src-server\protocol\technomasters.py", line 2100, in parse_structure
    data = parse_dictionary(data, ["session_token", "request"])
  File "D:\Bogi\Project\Compfie\Src-server\protocol\jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "D:\Bogi\Project\Compfie\Src-server\protocol\jsonvalidators.py", line 378, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "D:\Bogi\Project\Compfie\Src-server\protocol\jsonvalidators.py", line 279, in parse_values
    val = parse_string(val)
  File "D:\Bogi\Project\Compfie\Src-server\protocol\jsonvalidators.py", line 79, in parse_string
    raise empty_error()
ValueError: null is not allowed
 

2016-12-16 10:27:06,194 - knowledge_logger - main.py-handle-api- : null is not allowed 

2016-12-16 10:27:06,196 - knowledge_logger - main.py : Traceback (most recent call last):
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2016-12-16 12:57:50,729 - knowledge_logger - main.py-handle-api- : list index out of range 

2016-12-16 12:57:50,729 - knowledge_logger - main.py : Traceback (most recent call last):
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 203, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 315, in handle_techno
    return controller.process_techno_request(request, db)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\technocontroller.py", line 149, in process_techno_request
    result = get_unassigned_units(db, session_user)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\technomastercontroller.py", line 547, in get_unassigned_units
    units_list = get_unassigned_units_list(db, session_user)
  File "D:\Bogi\Project\Compfie\Src-server\server\database\technomaster.py", line 2044, in get_unassigned_units_list
    return return_unassigned_units(units[1])
IndexError: list index out of range
 

2016-12-16 12:57:57,948 - knowledge_logger - main.py-handle-api- : list index out of range 

2016-12-16 12:57:57,948 - knowledge_logger - main.py : Traceback (most recent call last):
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 203, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 315, in handle_techno
    return controller.process_techno_request(request, db)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\technocontroller.py", line 149, in process_techno_request
    result = get_unassigned_units(db, session_user)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\technomastercontroller.py", line 547, in get_unassigned_units
    units_list = get_unassigned_units_list(db, session_user)
  File "D:\Bogi\Project\Compfie\Src-server\server\database\technomaster.py", line 2044, in get_unassigned_units_list
    return return_unassigned_units(units[1])
IndexError: list index out of range
 

2016-12-16 13:00:08,766 - knowledge_logger - main.py-handle-api- : 'domain_ids' 

2016-12-16 13:00:08,766 - knowledge_logger - main.py : Traceback (most recent call last):
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 203, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 307, in handle_admin
    return controller.process_admin_request(request, db)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\admincontroller.py", line 116, in process_admin_request
    db, request_frame, session_user)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\admincontroller.py", line 514, in get_reassign_user_account_form_data
    units = get_units(db)
  File "D:\Bogi\Project\Compfie\Src-server\server\database\technomaster.py", line 1608, in get_units
    return return_units(result)
  File "D:\Bogi\Project\Compfie\Src-server\server\database\technomaster.py", line 1620, in return_units
    domain_ids = [int(x) for x in unit["domain_ids"].split(',') if x != '']
KeyError: 'domain_ids'
 

2016-12-16 13:01:15,365 - knowledge_logger - main.py-handle-api- : 'domain_ids' 

2016-12-16 13:01:15,365 - knowledge_logger - main.py : Traceback (most recent call last):
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 203, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 307, in handle_admin
    return controller.process_admin_request(request, db)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\admincontroller.py", line 116, in process_admin_request
    db, request_frame, session_user)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\admincontroller.py", line 514, in get_reassign_user_account_form_data
    units = get_units(db)
  File "D:\Bogi\Project\Compfie\Src-server\server\database\technomaster.py", line 1608, in get_units
    return return_units(result)
  File "D:\Bogi\Project\Compfie\Src-server\server\database\technomaster.py", line 1620, in return_units
    domain_ids = [int(x) for x in unit["domain_ids"].split(',') if x != '']
KeyError: 'domain_ids'
 

2016-12-16 13:01:24,176 - knowledge_logger - main.py-handle-api- : list index out of range 

2016-12-16 13:01:24,176 - knowledge_logger - main.py : Traceback (most recent call last):
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 203, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 360, in handle_techno_transaction
    return controller.process_techno_transaction_request(request, db)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\technotransactioncontroller.py", line 99, in process_techno_transaction_request
    result = process_get_groupadmingroup_unit_list(db, user_id)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\technotransactioncontroller.py", line 198, in process_get_groupadmingroup_unit_list
    groupadmin_groupsList = get_groupadmin_registration_grouplist(db, session_user)
  File "D:\Bogi\Project\Compfie\Src-server\server\database\technotransaction.py", line 493, in get_groupadmin_registration_grouplist
    return return_groupadmin_registration_grouplist(groupadmin_grouplist)
  File "D:\Bogi\Project\Compfie\Src-server\server\database\technotransaction.py", line 497, in return_groupadmin_registration_grouplist
    for groups in groupslist[1]:
IndexError: list index out of range
 

