2016-12-16 02:02:51,113 - knowledge_logger - main.py-parse-request : null is not allowed 

2016-12-16 02:02:51,115 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 2104, in parse_structure
    request, "technomasters", "Request"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 479, in parse_VariantType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 118, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 523, in parse_inner_structure
    "cl_id", "bg_id", "le_id", "c_id", "division_units", "units"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 378, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 286, in parse_values
    val = parse_number(val, 0, _length)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 50, in parse_number
    raise empty_error()
ValueError: null is not allowed
 

2016-12-16 02:02:51,115 - knowledge_logger - main.py-handle-api- : null is not allowed 

2016-12-16 02:02:51,115 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2016-12-16 02:06:10,489 - knowledge_logger - main.py-parse-request : null is not allowed 

2016-12-16 02:06:10,490 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 2104, in parse_structure
    request, "technomasters", "Request"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 479, in parse_VariantType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 118, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 523, in parse_inner_structure
    "cl_id", "bg_id", "le_id", "c_id", "division_units", "units"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 378, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 286, in parse_values
    val = parse_number(val, 0, _length)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 50, in parse_number
    raise empty_error()
ValueError: null is not allowed
 

2016-12-16 02:06:10,491 - knowledge_logger - main.py-handle-api- : null is not allowed 

2016-12-16 02:06:10,491 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2016-12-16 19:27:53,618 - knowledge_logger - main.py-parse-request : null is not allowed 

2016-12-16 19:27:53,635 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 2104, in parse_structure
    request, "technomasters", "Request"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 479, in parse_VariantType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 118, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 523, in parse_inner_structure
    "cl_id", "bg_id", "le_id", "c_id", "division_units", "units"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 378, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 286, in parse_values
    val = parse_number(val, 0, _length)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 50, in parse_number
    raise empty_error()
ValueError: null is not allowed
 

2016-12-16 19:27:53,636 - knowledge_logger - main.py-handle-api- : null is not allowed 

2016-12-16 19:27:53,636 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2016-12-16 19:32:26,183 - knowledge_logger - main.py-parse-request : null is not allowed 

2016-12-16 19:32:26,184 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 2104, in parse_structure
    request, "technomasters", "Request"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 479, in parse_VariantType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 118, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 523, in parse_inner_structure
    "cl_id", "bg_id", "le_id", "c_id", "division_units", "units"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 378, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 286, in parse_values
    val = parse_number(val, 0, _length)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 50, in parse_number
    raise empty_error()
ValueError: null is not allowed
 

2016-12-16 19:32:26,185 - knowledge_logger - main.py-handle-api- : null is not allowed 

2016-12-16 19:32:26,185 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2016-12-16 19:38:17,790 - knowledge_logger - main.py-parse-request : null is not allowed 

2016-12-16 19:38:17,792 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 2104, in parse_structure
    request, "technomasters", "Request"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 479, in parse_VariantType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 118, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 523, in parse_inner_structure
    "cl_id", "bg_id", "le_id", "c_id", "division_units", "units"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 378, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 286, in parse_values
    val = parse_number(val, 0, _length)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 50, in parse_number
    raise empty_error()
ValueError: null is not allowed
 

2016-12-16 19:38:17,794 - knowledge_logger - main.py-handle-api- : null is not allowed 

2016-12-16 19:38:17,795 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2016-12-16 19:40:49,359 - knowledge_logger - main.py-parse-request : null is not allowed 

2016-12-16 19:40:49,360 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 2104, in parse_structure
    request, "technomasters", "Request"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 479, in parse_VariantType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 118, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 523, in parse_inner_structure
    "cl_id", "bg_id", "le_id", "c_id", "division_units", "units"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 378, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 286, in parse_values
    val = parse_number(val, 0, _length)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 50, in parse_number
    raise empty_error()
ValueError: null is not allowed
 

2016-12-16 19:40:49,360 - knowledge_logger - main.py-handle-api- : null is not allowed 

2016-12-16 19:40:49,361 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2016-12-16 19:42:23,964 - knowledge_logger - main.py-parse-request : null is not allowed 

2016-12-16 19:42:23,964 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 2104, in parse_structure
    request, "technomasters", "Request"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 479, in parse_VariantType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 118, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 523, in parse_inner_structure
    "cl_id", "bg_id", "le_id", "c_id", "division_units", "units"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 378, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 286, in parse_values
    val = parse_number(val, 0, _length)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 50, in parse_number
    raise empty_error()
ValueError: null is not allowed
 

2016-12-16 19:42:23,965 - knowledge_logger - main.py-handle-api- : null is not allowed 

2016-12-16 19:42:23,965 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2016-12-16 19:46:12,782 - knowledge_logger - main.py-parse-request : null is not allowed 

2016-12-16 19:46:12,783 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 2104, in parse_structure
    request, "technomasters", "Request"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 479, in parse_VariantType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 118, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 523, in parse_inner_structure
    "cl_id", "bg_id", "le_id", "c_id", "division_units", "units"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 378, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 286, in parse_values
    val = parse_number(val, 0, _length)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 50, in parse_number
    raise empty_error()
ValueError: null is not allowed
 

2016-12-16 19:46:12,784 - knowledge_logger - main.py-handle-api- : null is not allowed 

2016-12-16 19:46:12,784 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2016-12-16 19:48:13,957 - knowledge_logger - main.py-parse-request : null is not allowed 

2016-12-16 19:48:13,957 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 2104, in parse_structure
    request, "technomasters", "Request"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 479, in parse_VariantType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 118, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 523, in parse_inner_structure
    "cl_id", "bg_id", "le_id", "c_id", "division_units", "units"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 378, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 286, in parse_values
    val = parse_number(val, 0, _length)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 50, in parse_number
    raise empty_error()
ValueError: null is not allowed
 

2016-12-16 19:48:13,958 - knowledge_logger - main.py-handle-api- : null is not allowed 

2016-12-16 19:48:13,958 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2016-12-16 20:15:02,252 - knowledge_logger - main.py-parse-request : null is not allowed 

2016-12-16 20:15:02,255 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 2104, in parse_structure
    request, "technomasters", "Request"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 479, in parse_VariantType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 118, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 523, in parse_inner_structure
    "cl_id", "bg_id", "le_id", "c_id", "division_units", "units"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 378, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 286, in parse_values
    val = parse_number(val, 0, _length)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 50, in parse_number
    raise empty_error()
ValueError: null is not allowed
 

2016-12-16 20:15:02,255 - knowledge_logger - main.py-handle-api- : null is not allowed 

2016-12-16 20:15:02,255 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2016-12-16 20:43:49,168 - knowledge_logger - main.py-parse-request : null is not allowed 

2016-12-16 20:43:49,169 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 2104, in parse_structure
    request, "technomasters", "Request"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 479, in parse_VariantType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 118, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 523, in parse_inner_structure
    "cl_id", "bg_id", "le_id", "c_id", "division_units", "units"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 378, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 286, in parse_values
    val = parse_number(val, 0, _length)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 50, in parse_number
    raise empty_error()
ValueError: null is not allowed
 

2016-12-16 20:43:49,170 - knowledge_logger - main.py-handle-api- : null is not allowed 

2016-12-16 20:43:49,170 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2016-12-16 20:47:29,074 - knowledge_logger - main.py-parse-request : null is not allowed 

2016-12-16 20:47:29,074 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 2104, in parse_structure
    request, "technomasters", "Request"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 479, in parse_VariantType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 118, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 523, in parse_inner_structure
    "cl_id", "bg_id", "le_id", "c_id", "division_units", "units"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 378, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 286, in parse_values
    val = parse_number(val, 0, _length)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 50, in parse_number
    raise empty_error()
ValueError: null is not allowed
 

2016-12-16 20:47:29,075 - knowledge_logger - main.py-handle-api- : null is not allowed 

2016-12-16 20:47:29,075 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2016-12-16 20:52:58,238 - knowledge_logger - main.py-parse-request : null is not allowed 

2016-12-16 20:52:58,239 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 2104, in parse_structure
    request, "technomasters", "Request"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 479, in parse_VariantType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 118, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 523, in parse_inner_structure
    "cl_id", "bg_id", "le_id", "c_id", "division_units", "units"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 378, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 286, in parse_values
    val = parse_number(val, 0, _length)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 50, in parse_number
    raise empty_error()
ValueError: null is not allowed
 

2016-12-16 20:52:58,239 - knowledge_logger - main.py-handle-api- : null is not allowed 

2016-12-16 20:52:58,240 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2016-12-16 20:55:02,762 - knowledge_logger - main.py-parse-request : null is not allowed 

2016-12-16 20:55:02,763 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 2104, in parse_structure
    request, "technomasters", "Request"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 479, in parse_VariantType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 118, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 523, in parse_inner_structure
    "cl_id", "bg_id", "le_id", "c_id", "division_units", "units"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 378, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 286, in parse_values
    val = parse_number(val, 0, _length)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 50, in parse_number
    raise empty_error()
ValueError: null is not allowed
 

2016-12-16 20:55:02,763 - knowledge_logger - main.py-handle-api- : null is not allowed 

2016-12-16 20:55:02,763 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2016-12-16 22:57:15,528 - knowledge_logger - main.py-parse-request : null is not allowed 

2016-12-16 22:57:15,528 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 2104, in parse_structure
    request, "technomasters", "Request"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 483, in parse_VariantType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 118, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 523, in parse_inner_structure
    "cl_id", "bg_id", "le_id", "c_id", "division_units", "units"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 382, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 290, in parse_values
    val = parse_number(val, 0, _length)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 50, in parse_number
    raise empty_error()
ValueError: null is not allowed
 

2016-12-16 22:57:15,529 - knowledge_logger - main.py-handle-api- : null is not allowed 

2016-12-16 22:57:15,529 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2016-12-16 23:01:34,292 - knowledge_logger - main.py-parse-request : expected a list with integer values , but received: [u'3'] 

2016-12-16 23:01:34,294 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 2104, in parse_structure
    request, "technomasters", "Request"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 483, in parse_VariantType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 118, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 523, in parse_inner_structure
    "cl_id", "bg_id", "le_id", "c_id", "division_units", "units"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 339, in parse_dictionary_values
    _module_name, _class_name, val
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 507, in parse_VectorType
    parse_RecordType(module_name, class_name, item)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 493, in parse_RecordType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 462, in parse_structure
    "i_ids_list"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 382, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 315, in parse_values
    val = parse_int_list(val, int_length=_length)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 242, in parse_int_list
    raise expectation_error("a list with integer values ", x)
ValueError: expected a list with integer values , but received: [u'3']
 

2016-12-16 23:01:34,294 - knowledge_logger - main.py-handle-api- : expected a list with integer values , but received: [u'3'] 

2016-12-16 23:01:34,294 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: expected a list with integer values , but received: [u'3']
 

2016-12-16 23:11:48,431 - knowledge_logger - main.py-parse-request : expected a list with integer values , but received: [u'3'] 

2016-12-16 23:11:48,432 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 2104, in parse_structure
    request, "technomasters", "Request"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 483, in parse_VariantType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 118, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 523, in parse_inner_structure
    "cl_id", "bg_id", "le_id", "c_id", "division_units", "units"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 339, in parse_dictionary_values
    _module_name, _class_name, val
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 507, in parse_VectorType
    parse_RecordType(module_name, class_name, item)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 493, in parse_RecordType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 462, in parse_structure
    "i_ids_list"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 382, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 315, in parse_values
    val = parse_int_list(val, int_length=_length)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 242, in parse_int_list
    raise expectation_error("a list with integer values ", x)
ValueError: expected a list with integer values , but received: [u'3']
 

2016-12-16 23:11:48,433 - knowledge_logger - main.py-handle-api- : expected a list with integer values , but received: [u'3'] 

2016-12-16 23:11:48,433 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: expected a list with integer values , but received: [u'3']
 

2016-12-16 23:16:51,472 - knowledge_logger - main.py-parse-request : expected a list with integer values , but received: [u'3'] 

2016-12-16 23:16:51,473 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 2104, in parse_structure
    request, "technomasters", "Request"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 483, in parse_VariantType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 118, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 523, in parse_inner_structure
    "cl_id", "bg_id", "le_id", "c_id", "division_units", "units"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 339, in parse_dictionary_values
    _module_name, _class_name, val
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 507, in parse_VectorType
    parse_RecordType(module_name, class_name, item)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 493, in parse_RecordType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 462, in parse_structure
    "i_ids_list"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 382, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 315, in parse_values
    val = parse_int_list(val, int_length=_length)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 242, in parse_int_list
    raise expectation_error("a list with integer values ", x)
ValueError: expected a list with integer values , but received: [u'3']
 

2016-12-16 23:16:51,473 - knowledge_logger - main.py-handle-api- : expected a list with integer values , but received: [u'3'] 

2016-12-16 23:16:51,474 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: expected a list with integer values , but received: [u'3']
 

2016-12-16 23:19:24,197 - knowledge_logger - main.py-parse-request : expected a list with integer values , but received: [u'3'] 

2016-12-16 23:19:24,198 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 2104, in parse_structure
    request, "technomasters", "Request"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 483, in parse_VariantType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 118, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 523, in parse_inner_structure
    "cl_id", "bg_id", "le_id", "c_id", "division_units", "units"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 339, in parse_dictionary_values
    _module_name, _class_name, val
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 507, in parse_VectorType
    parse_RecordType(module_name, class_name, item)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 493, in parse_RecordType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 462, in parse_structure
    "i_ids_list"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 382, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 315, in parse_values
    val = parse_int_list(val, int_length=_length)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 242, in parse_int_list
    raise expectation_error("a list with integer values ", x)
ValueError: expected a list with integer values , but received: [u'3']
 

2016-12-16 23:19:24,198 - knowledge_logger - main.py-handle-api- : expected a list with integer values , but received: [u'3'] 

2016-12-16 23:19:24,199 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: expected a list with integer values , but received: [u'3']
 

2016-12-16 23:20:26,452 - knowledge_logger - main.py-parse-request : expected a dict, but received: 3 

2016-12-16 23:20:26,453 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 2104, in parse_structure
    request, "technomasters", "Request"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 483, in parse_VariantType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 118, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 523, in parse_inner_structure
    "cl_id", "bg_id", "le_id", "c_id", "division_units", "units"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 339, in parse_dictionary_values
    _module_name, _class_name, val
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 507, in parse_VectorType
    parse_RecordType(module_name, class_name, item)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 493, in parse_RecordType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 462, in parse_structure
    "i_ids_list"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 339, in parse_dictionary_values
    _module_name, _class_name, val
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 507, in parse_VectorType
    parse_RecordType(module_name, class_name, item)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 493, in parse_RecordType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/core.py", line 3711, in parse_structure
    data = parse_dictionary(data, ["domain_id", "industry_id"])
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 181, in parse_dictionary
    raise expectation_error("a dict", x)
ValueError: expected a dict, but received: 3
 

2016-12-16 23:20:26,453 - knowledge_logger - main.py-handle-api- : expected a dict, but received: 3 

2016-12-16 23:20:26,454 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: expected a dict, but received: 3
 

2016-12-16 23:22:09,571 - knowledge_logger - main.py-parse-request : expected a dict, but received: 3 

2016-12-16 23:22:09,572 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 2104, in parse_structure
    request, "technomasters", "Request"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 483, in parse_VariantType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 118, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 523, in parse_inner_structure
    "cl_id", "bg_id", "le_id", "c_id", "division_units", "units"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 339, in parse_dictionary_values
    _module_name, _class_name, val
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 507, in parse_VectorType
    parse_RecordType(module_name, class_name, item)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 493, in parse_RecordType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 462, in parse_structure
    "i_ids_list"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 339, in parse_dictionary_values
    _module_name, _class_name, val
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 507, in parse_VectorType
    parse_RecordType(module_name, class_name, item)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 493, in parse_RecordType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/core.py", line 3711, in parse_structure
    data = parse_dictionary(data, ["domain_id", "industry_id"])
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 181, in parse_dictionary
    raise expectation_error("a dict", x)
ValueError: expected a dict, but received: 3
 

2016-12-16 23:22:09,573 - knowledge_logger - main.py-handle-api- : expected a dict, but received: 3 

2016-12-16 23:22:09,573 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: expected a dict, but received: 3
 

2016-12-16 23:25:28,075 - knowledge_logger - main.py-parse-request : expected a list with integer values , but received: [{u'd_id': 3}] 

2016-12-16 23:25:28,076 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 2104, in parse_structure
    request, "technomasters", "Request"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 483, in parse_VariantType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 118, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 523, in parse_inner_structure
    "cl_id", "bg_id", "le_id", "c_id", "division_units", "units"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 339, in parse_dictionary_values
    _module_name, _class_name, val
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 507, in parse_VectorType
    parse_RecordType(module_name, class_name, item)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 493, in parse_RecordType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 462, in parse_structure
    "i_ids_list"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 382, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 315, in parse_values
    val = parse_int_list(val, int_length=_length)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 242, in parse_int_list
    raise expectation_error("a list with integer values ", x)
ValueError: expected a list with integer values , but received: [{u'd_id': 3}]
 

2016-12-16 23:25:28,078 - knowledge_logger - main.py-handle-api- : expected a list with integer values , but received: [{u'd_id': 3}] 

2016-12-16 23:25:28,078 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: expected a list with integer values , but received: [{u'd_id': 3}]
 

2016-12-16 23:27:09,935 - knowledge_logger - main.py-parse-request : expected a dict, but received: 3 

2016-12-16 23:27:09,937 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 2104, in parse_structure
    request, "technomasters", "Request"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 483, in parse_VariantType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 118, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 523, in parse_inner_structure
    "cl_id", "bg_id", "le_id", "c_id", "division_units", "units"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 339, in parse_dictionary_values
    _module_name, _class_name, val
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 507, in parse_VectorType
    parse_RecordType(module_name, class_name, item)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 493, in parse_RecordType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 462, in parse_structure
    "i_ids_list"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 339, in parse_dictionary_values
    _module_name, _class_name, val
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 507, in parse_VectorType
    parse_RecordType(module_name, class_name, item)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 493, in parse_RecordType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/core.py", line 3711, in parse_structure
    data = parse_dictionary(data, ["domain_id", "industry_id"])
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 181, in parse_dictionary
    raise expectation_error("a dict", x)
ValueError: expected a dict, but received: 3
 

2016-12-16 23:27:09,938 - knowledge_logger - main.py-handle-api- : expected a dict, but received: 3 

2016-12-16 23:27:09,938 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: expected a dict, but received: 3
 

2016-12-16 23:29:41,747 - knowledge_logger - main.py-parse-request : expected a dict, but received: 2 

2016-12-16 23:29:41,748 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 2104, in parse_structure
    request, "technomasters", "Request"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 483, in parse_VariantType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 118, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 523, in parse_inner_structure
    "cl_id", "bg_id", "le_id", "c_id", "division_units", "units"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 339, in parse_dictionary_values
    _module_name, _class_name, val
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 507, in parse_VectorType
    parse_RecordType(module_name, class_name, item)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 493, in parse_RecordType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 462, in parse_structure
    "i_ids_list"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 339, in parse_dictionary_values
    _module_name, _class_name, val
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 507, in parse_VectorType
    parse_RecordType(module_name, class_name, item)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 493, in parse_RecordType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/core.py", line 3711, in parse_structure
    data = parse_dictionary(data, ["domain_id", "industry_id"])
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 181, in parse_dictionary
    raise expectation_error("a dict", x)
ValueError: expected a dict, but received: 2
 

2016-12-16 23:29:41,749 - knowledge_logger - main.py-handle-api- : expected a dict, but received: 2 

2016-12-16 23:29:41,749 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: expected a dict, but received: 2
 

2016-12-16 23:31:51,098 - knowledge_logger - main.py-parse-request : expected a dict, but received: 3 

2016-12-16 23:31:51,099 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 2104, in parse_structure
    request, "technomasters", "Request"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 483, in parse_VariantType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 118, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 523, in parse_inner_structure
    "cl_id", "bg_id", "le_id", "c_id", "division_units", "units"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 339, in parse_dictionary_values
    _module_name, _class_name, val
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 507, in parse_VectorType
    parse_RecordType(module_name, class_name, item)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 493, in parse_RecordType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 462, in parse_structure
    "i_ids_list"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 339, in parse_dictionary_values
    _module_name, _class_name, val
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 507, in parse_VectorType
    parse_RecordType(module_name, class_name, item)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 493, in parse_RecordType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/core.py", line 3711, in parse_structure
    data = parse_dictionary(data, ["domain_id", "industry_id"])
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 181, in parse_dictionary
    raise expectation_error("a dict", x)
ValueError: expected a dict, but received: 3
 

2016-12-16 23:31:51,100 - knowledge_logger - main.py-handle-api- : expected a dict, but received: 3 

2016-12-16 23:31:51,100 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: expected a dict, but received: 3
 

2016-12-16 23:36:29,441 - knowledge_logger - main.py-parse-request : expected a dict, but received: 3 

2016-12-16 23:36:29,442 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 2104, in parse_structure
    request, "technomasters", "Request"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 483, in parse_VariantType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 118, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 523, in parse_inner_structure
    "cl_id", "bg_id", "le_id", "c_id", "division_units", "units"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 339, in parse_dictionary_values
    _module_name, _class_name, val
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 507, in parse_VectorType
    parse_RecordType(module_name, class_name, item)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 493, in parse_RecordType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/technomasters.py", line 462, in parse_structure
    "i_ids_list"
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 339, in parse_dictionary_values
    _module_name, _class_name, val
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 507, in parse_VectorType
    parse_RecordType(module_name, class_name, item)
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 493, in parse_RecordType
    return klass.parse_structure(data)
  File "/home/usha/aparajitha-saas/Src-server/protocol/core.py", line 3711, in parse_structure
    data = parse_dictionary(data, ["domain_id", "industry_id"])
  File "/home/usha/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 181, in parse_dictionary
    raise expectation_error("a dict", x)
ValueError: expected a dict, but received: 3
 

2016-12-16 23:36:29,442 - knowledge_logger - main.py-handle-api- : expected a dict, but received: 3 

2016-12-16 23:36:29,442 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/usha/aparajitha-saas/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: expected a dict, but received: 3
 

