2016-03-29 15:20:04,958 - knowledge_logger - main.py-handle-api- : unexpected end of regular expression
2016-03-29 15:20:04,958 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/main.py", line 131, in handle_api_request
    response_data = unbound_method(self, request_data, self._db)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/main.py", line 185, in handle_techno
    return controller.process_techno_request(request, db)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/controller/technocontroller.py", line 39, in process_techno_request
    return save_client_group(db, request_frame, session_user)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/controller/technomastercontroller.py", line 86, in save_client_group
    short_name = re.sub('[^a-zA-Z0-9 \n\]', '', request.short_name)
  File "/usr/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib/python2.7/re.py", line 244, in _compile
    raise error, v # invalid expression
error: unexpected end of regular expression

