2016-03-22 10:25:26,143 - knowledge_logger - main.py-handle-api : (1452, 'Cannot add or update a child row: a foreign key constraint fails (`compfie_knowledge`.`tbl_activity_log`, CONSTRAINT `fk_activity_log_forms` FOREIGN KEY (`form_id`) REFERENCES `tbl_forms` (`form_id`))')
2016-03-22 10:25:26,161 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/king/projects/aparajitha-saas/Src-server/server/main.py", line 129, in handle_api_request
    response_data = unbound_method(self, request_data, self._db)
  File "/home/king/projects/aparajitha-saas/Src-server/server/main.py", line 172, in handle_login
    return controller.process_login_request(request, db)
  File "/home/king/projects/aparajitha-saas/Src-server/server/controller/logincontroller.py", line 21, in process_login_request
    return process_login(db, request)
  File "/home/king/projects/aparajitha-saas/Src-server/server/controller/logincontroller.py", line 48, in process_login
    return user_login_response(db, response, request.ip)
  File "/home/king/projects/aparajitha-saas/Src-server/server/controller/logincontroller.py", line 60, in user_login_response
    session_token = db.add_session(user_id, session_type, ip, employee)
  File "/home/king/projects/aparajitha-saas/Src-server/server/database.py", line 444, in add_session
    self.save_activity(user_id, 0, action)
  File "/home/king/projects/aparajitha-saas/Src-server/server/database.py", line 600, in save_activity
    self.execute(query)
  File "/home/king/projects/aparajitha-saas/Src-server/server/database.py", line 157, in execute
    return cursor.execute(query)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`compfie_knowledge`.`tbl_activity_log`, CONSTRAINT `fk_activity_log_forms` FOREIGN KEY (`form_id`) REFERENCES `tbl_forms` (`form_id`))')

2016-03-22 12:02:07,465 - knowledge_logger - main.py-parse-request : null is not allowed
2016-03-22 12:02:07,491 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/king/projects/aparajitha-saas/Src-server/server/main.py", line 98, in _parse_request
    data
  File "/home/king/projects/aparajitha-saas/Src-server/protocol/technomasters.py", line 1302, in parse_structure
    request = parse_structure_VariantType_technomasters_Request(request)
  File "/home/king/projects/aparajitha-saas/Src-server/protocol/parse_structure.py", line 346, in parse_structure_VariantType_technomasters_Request
    return technomasters.Request.parse_structure(data)
  File "/home/king/projects/aparajitha-saas/Src-server/protocol/technomasters.py", line 110, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/king/projects/aparajitha-saas/Src-server/protocol/technomasters.py", line 554, in parse_inner_structure
    client_id = parse_structure_UnsignedIntegerType_32(client_id)
  File "/home/king/projects/aparajitha-saas/Src-server/protocol/parse_structure.py", line 289, in parse_structure_UnsignedIntegerType_32
    return parse_number(data, 0, 4294967295)
  File "/home/king/projects/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 38, in parse_number
    raise empty_error()
ValueError: null is not allowed

