2016-12-10 10:35:09,846 - knowledge_logger - main.py-handle-api- : list index out of range 

2016-12-10 10:35:09,868 - knowledge_logger - main.py : Traceback (most recent call last):
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 203, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 360, in handle_techno_transaction
    return controller.process_techno_transaction_request(request, db)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\technotransactioncontroller.py", line 99, in process_techno_transaction_request
    result = process_get_groupadmingroup_unit_list(db, user_id)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\technotransactioncontroller.py", line 198, in process_get_groupadmingroup_unit_list
    groupadmin_groupsList = get_groupadmin_registration_grouplist(db, session_user)
  File "D:\Bogi\Project\Compfie\Src-server\server\database\technotransaction.py", line 493, in get_groupadmin_registration_grouplist
    return return_groupadmin_registration_grouplist(groupadmin_grouplist)
  File "D:\Bogi\Project\Compfie\Src-server\server\database\technotransaction.py", line 497, in return_groupadmin_registration_grouplist
    for groups in groupslist[1]:
IndexError: list index out of range
 

2016-12-10 13:03:45,395 - knowledge_logger - main.py-handle-api- : list index out of range 

2016-12-10 13:03:45,395 - knowledge_logger - main.py : Traceback (most recent call last):
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 203, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 315, in handle_techno
    return controller.process_techno_request(request, db)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\technocontroller.py", line 149, in process_techno_request
    result = get_unassigned_units(db, session_user)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\technomastercontroller.py", line 547, in get_unassigned_units
    units_list = get_unassigned_units_list(db, session_user)
  File "D:\Bogi\Project\Compfie\Src-server\server\database\technomaster.py", line 2044, in get_unassigned_units_list
    return return_unassigned_units(units[1])
IndexError: list index out of range
 

2016-12-10 13:19:48,795 - knowledge_logger - main.py-handle-api- : list index out of range 

2016-12-10 13:19:48,795 - knowledge_logger - main.py : Traceback (most recent call last):
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 203, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 315, in handle_techno
    return controller.process_techno_request(request, db)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\technocontroller.py", line 149, in process_techno_request
    result = get_unassigned_units(db, session_user)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\technomastercontroller.py", line 547, in get_unassigned_units
    units_list = get_unassigned_units_list(db, session_user)
  File "D:\Bogi\Project\Compfie\Src-server\server\database\technomaster.py", line 2044, in get_unassigned_units_list
    return return_unassigned_units(units[1])
IndexError: list index out of range
 

2016-12-10 17:14:56,357 - knowledge_logger - main.py-parse-request : null is not allowed 

2016-12-10 17:14:56,460 - knowledge_logger - main.py : Traceback (most recent call last):
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 155, in _parse_request
    data
  File "D:\Bogi\Project\Compfie\Src-server\protocol\technoreports.py", line 1137, in parse_structure
    data = parse_dictionary(data, ["session_token", "request"])
  File "D:\Bogi\Project\Compfie\Src-server\protocol\jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "D:\Bogi\Project\Compfie\Src-server\protocol\jsonvalidators.py", line 378, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "D:\Bogi\Project\Compfie\Src-server\protocol\jsonvalidators.py", line 279, in parse_values
    val = parse_string(val)
  File "D:\Bogi\Project\Compfie\Src-server\protocol\jsonvalidators.py", line 79, in parse_string
    raise empty_error()
ValueError: null is not allowed
 

2016-12-10 17:14:56,466 - knowledge_logger - main.py-handle-api- : null is not allowed 

2016-12-10 17:14:56,467 - knowledge_logger - main.py : Traceback (most recent call last):
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

