2016-12-13 11:21:11,230 - knowledge_logger - main.py-parse-request : expected a number between 0 and 1000000, but received: 6253001 

2016-12-13 11:21:11,280 - knowledge_logger - main.py : Traceback (most recent call last):
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 155, in _parse_request
    data
  File "D:\Bogi\Project\Compfie\Src-server\protocol\technomasters.py", line 2104, in parse_structure
    request, "technomasters", "Request"
  File "D:\Bogi\Project\Compfie\Src-server\protocol\jsonvalidators.py", line 479, in parse_VariantType
    return klass.parse_structure(data)
  File "D:\Bogi\Project\Compfie\Src-server\protocol\technomasters.py", line 118, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "D:\Bogi\Project\Compfie\Src-server\protocol\technomasters.py", line 523, in parse_inner_structure
    "cl_id", "bg_id", "le_id", "c_id", "division_units", "units"
  File "D:\Bogi\Project\Compfie\Src-server\protocol\jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "D:\Bogi\Project\Compfie\Src-server\protocol\jsonvalidators.py", line 335, in parse_dictionary_values
    _module_name, _class_name, val
  File "D:\Bogi\Project\Compfie\Src-server\protocol\jsonvalidators.py", line 503, in parse_VectorType
    parse_RecordType(module_name, class_name, item)
  File "D:\Bogi\Project\Compfie\Src-server\protocol\jsonvalidators.py", line 489, in parse_RecordType
    return klass.parse_structure(data)
  File "D:\Bogi\Project\Compfie\Src-server\protocol\technomasters.py", line 462, in parse_structure
    "i_ids_list"
  File "D:\Bogi\Project\Compfie\Src-server\protocol\jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "D:\Bogi\Project\Compfie\Src-server\protocol\jsonvalidators.py", line 378, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "D:\Bogi\Project\Compfie\Src-server\protocol\jsonvalidators.py", line 286, in parse_values
    val = parse_number(val, 0, _length)
  File "D:\Bogi\Project\Compfie\Src-server\protocol\jsonvalidators.py", line 60, in parse_number
    raise expectation_error(msg, x)
ValueError: expected a number between 0 and 1000000, but received: 6253001
 

2016-12-13 11:21:11,280 - knowledge_logger - main.py-handle-api- : expected a number between 0 and 1000000, but received: 6253001 

2016-12-13 11:21:11,280 - knowledge_logger - main.py : Traceback (most recent call last):
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: expected a number between 0 and 1000000, but received: 6253001
 

2016-12-13 12:35:21,253 - knowledge_logger - main.py-parse-request : expected a number between 0 and 1000000, but received: 3564354 

2016-12-13 12:35:21,253 - knowledge_logger - main.py : Traceback (most recent call last):
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 155, in _parse_request
    data
  File "D:\Bogi\Project\Compfie\Src-server\protocol\technomasters.py", line 2104, in parse_structure
    request, "technomasters", "Request"
  File "D:\Bogi\Project\Compfie\Src-server\protocol\jsonvalidators.py", line 479, in parse_VariantType
    return klass.parse_structure(data)
  File "D:\Bogi\Project\Compfie\Src-server\protocol\technomasters.py", line 118, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "D:\Bogi\Project\Compfie\Src-server\protocol\technomasters.py", line 523, in parse_inner_structure
    "cl_id", "bg_id", "le_id", "c_id", "division_units", "units"
  File "D:\Bogi\Project\Compfie\Src-server\protocol\jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "D:\Bogi\Project\Compfie\Src-server\protocol\jsonvalidators.py", line 335, in parse_dictionary_values
    _module_name, _class_name, val
  File "D:\Bogi\Project\Compfie\Src-server\protocol\jsonvalidators.py", line 503, in parse_VectorType
    parse_RecordType(module_name, class_name, item)
  File "D:\Bogi\Project\Compfie\Src-server\protocol\jsonvalidators.py", line 489, in parse_RecordType
    return klass.parse_structure(data)
  File "D:\Bogi\Project\Compfie\Src-server\protocol\technomasters.py", line 462, in parse_structure
    "i_ids_list"
  File "D:\Bogi\Project\Compfie\Src-server\protocol\jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "D:\Bogi\Project\Compfie\Src-server\protocol\jsonvalidators.py", line 378, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "D:\Bogi\Project\Compfie\Src-server\protocol\jsonvalidators.py", line 286, in parse_values
    val = parse_number(val, 0, _length)
  File "D:\Bogi\Project\Compfie\Src-server\protocol\jsonvalidators.py", line 60, in parse_number
    raise expectation_error(msg, x)
ValueError: expected a number between 0 and 1000000, but received: 3564354
 

2016-12-13 12:35:21,263 - knowledge_logger - main.py-handle-api- : expected a number between 0 and 1000000, but received: 3564354 

2016-12-13 12:35:21,263 - knowledge_logger - main.py : Traceback (most recent call last):
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: expected a number between 0 and 1000000, but received: 3564354
 

