2016-12-21 11:30:42,177 - knowledge_logger - main.py-handle-api- : Unread result found 

2016-12-21 11:30:42,182 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 209, in handle_api_request
    _db.commit()
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/dbase.py", line 171, in commit
    self._cursor.close()
  File "/home/ushadevi/.local/lib/python2.7/site-packages/mysql/connector/cursor.py", line 344, in close
    self._connection.handle_unread_result()
  File "/home/ushadevi/.local/lib/python2.7/site-packages/mysql/connector/connection.py", line 1057, in handle_unread_result
    raise errors.InternalError("Unread result found")
InternalError: Unread result found
 

2016-12-21 11:42:41,044 - knowledge_logger - main.py-parse-request : expected a alphanumerics, but received: ' 7g  

2016-12-21 11:42:41,045 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/mobile.py", line 1300, in parse_structure
    request = parse_structure_VariantType_mobile_Request(request)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/parse_structure.py", line 2213, in parse_structure_VariantType_mobile_Request
    return mobile.Request.parse_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/mobile.py", line 80, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/mobile.py", line 454, in parse_inner_structure
    data = parse_dictionary(data, ["s_mappings"])
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 336, in parse_dictionary_values
    _module_name, _class_name, val
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 503, in parse_VectorType
    parse_RecordType(module_name, class_name, item)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 489, in parse_RecordType
    return klass.parse_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 1114, in parse_structure
    "comp_id", "is_common", "u_by"
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 385, in parse_dictionary_values
    val = _validation_method(val)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/api_key_validation.py", line 37, in is_alpha_numeric
    raise expectation_error('a alphanumerics', value)
ValueError: expected a alphanumerics, but received: ' 7g 
 

2016-12-21 11:42:41,047 - knowledge_logger - main.py-handle-api- : expected a alphanumerics, but received: ' 7g  

2016-12-21 11:42:41,047 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: expected a alphanumerics, but received: ' 7g 
 

2016-12-21 12:00:40,625 - knowledge_logger - main.py-handle-api- : Transaction failed while processing data. 

2016-12-21 12:00:40,626 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 202, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 343, in handle_knowledge_report
    return controller.process_knowledge_report_request(request, db)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/controller/knowledgereportcontroller.py", line 61, in process_knowledge_report_request
    db, request_frame, user_id
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/controller/knowledgereportcontroller.py", line 118, in process_get_statutory_mapping_report_data
    from_count, to_count
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/database/knowledgereport.py", line 151, in get_statutory_mapping_report
    rows = db.select_all(q + order, param_lst)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/dbase.py", line 298, in select_all
    raise fetch_error()
RuntimeError: Transaction failed while processing data.
 

2016-12-21 12:11:22,200 - knowledge_logger - main.py-handle-api- : Transaction failed while processing data. 

2016-12-21 12:11:22,200 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 202, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 343, in handle_knowledge_report
    return controller.process_knowledge_report_request(request, db)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/controller/knowledgereportcontroller.py", line 61, in process_knowledge_report_request
    db, request_frame, user_id
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/controller/knowledgereportcontroller.py", line 118, in process_get_statutory_mapping_report_data
    from_count, to_count
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/database/knowledgereport.py", line 151, in get_statutory_mapping_report
    rows = db.select_all(q + order, param_lst)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/dbase.py", line 298, in select_all
    raise fetch_error()
RuntimeError: Transaction failed while processing data.
 

2016-12-21 12:54:47,222 - knowledge_logger - main.py-parse-request : null is not allowed 

2016-12-21 12:54:47,223 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 802, in parse_structure
    request = parse_structure_VariantType_knowledgetransaction_Request(request)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/parse_structure.py", line 736, in parse_structure_VariantType_knowledgetransaction_Request
    return knowledgetransaction.Request.parse_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 34, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 59, in parse_inner_structure
    data = parse_dictionary(data, ["approval_status_id", "rcount"])
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 379, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 287, in parse_values
    val = parse_number(val, 0, _length)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 50, in parse_number
    raise empty_error()
ValueError: null is not allowed
 

2016-12-21 12:54:47,224 - knowledge_logger - main.py-handle-api- : null is not allowed 

2016-12-21 12:54:47,224 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2016-12-21 12:55:27,537 - knowledge_logger - main.py-parse-request : null is not allowed 

2016-12-21 12:55:27,537 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 802, in parse_structure
    request = parse_structure_VariantType_knowledgetransaction_Request(request)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/parse_structure.py", line 736, in parse_structure_VariantType_knowledgetransaction_Request
    return knowledgetransaction.Request.parse_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 34, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 59, in parse_inner_structure
    data = parse_dictionary(data, ["approval_status_id", "rcount"])
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 379, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 287, in parse_values
    val = parse_number(val, 0, _length)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 50, in parse_number
    raise empty_error()
ValueError: null is not allowed
 

2016-12-21 12:55:27,538 - knowledge_logger - main.py-handle-api- : null is not allowed 

2016-12-21 12:55:27,538 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2016-12-21 13:05:57,577 - knowledge_logger - main.py-parse-request : null is not allowed 

2016-12-21 13:05:57,577 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 802, in parse_structure
    request = parse_structure_VariantType_knowledgetransaction_Request(request)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/parse_structure.py", line 736, in parse_structure_VariantType_knowledgetransaction_Request
    return knowledgetransaction.Request.parse_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 34, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 59, in parse_inner_structure
    data = parse_dictionary(data, ["approval_status_id", "rcount"])
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 379, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 287, in parse_values
    val = parse_number(val, 0, _length)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 50, in parse_number
    raise empty_error()
ValueError: null is not allowed
 

2016-12-21 13:05:57,578 - knowledge_logger - main.py-handle-api- : null is not allowed 

2016-12-21 13:05:57,579 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2016-12-21 13:06:15,950 - knowledge_logger - main.py-parse-request : null is not allowed 

2016-12-21 13:06:15,951 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 802, in parse_structure
    request = parse_structure_VariantType_knowledgetransaction_Request(request)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/parse_structure.py", line 736, in parse_structure_VariantType_knowledgetransaction_Request
    return knowledgetransaction.Request.parse_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 34, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 59, in parse_inner_structure
    data = parse_dictionary(data, ["approval_status_id", "rcount"])
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 379, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 287, in parse_values
    val = parse_number(val, 0, _length)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 50, in parse_number
    raise empty_error()
ValueError: null is not allowed
 

2016-12-21 13:06:15,951 - knowledge_logger - main.py-handle-api- : null is not allowed 

2016-12-21 13:06:15,952 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2016-12-21 13:22:38,743 - knowledge_logger - main.py-parse-request : null is not allowed 

2016-12-21 13:22:38,744 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 802, in parse_structure
    request = parse_structure_VariantType_knowledgetransaction_Request(request)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/parse_structure.py", line 736, in parse_structure_VariantType_knowledgetransaction_Request
    return knowledgetransaction.Request.parse_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 34, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 59, in parse_inner_structure
    data = parse_dictionary(data, ["approval_status_id", "rcount"])
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 379, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 287, in parse_values
    val = parse_number(val, 0, _length)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 50, in parse_number
    raise empty_error()
ValueError: null is not allowed
 

2016-12-21 13:22:38,744 - knowledge_logger - main.py-handle-api- : null is not allowed 

2016-12-21 13:22:38,744 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2016-12-21 13:23:27,912 - knowledge_logger - main.py-parse-request : null is not allowed 

2016-12-21 13:23:27,912 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 802, in parse_structure
    request = parse_structure_VariantType_knowledgetransaction_Request(request)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/parse_structure.py", line 736, in parse_structure_VariantType_knowledgetransaction_Request
    return knowledgetransaction.Request.parse_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 34, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 59, in parse_inner_structure
    data = parse_dictionary(data, ["approval_status_id", "rcount"])
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 379, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 287, in parse_values
    val = parse_number(val, 0, _length)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 50, in parse_number
    raise empty_error()
ValueError: null is not allowed
 

2016-12-21 13:23:27,912 - knowledge_logger - main.py-handle-api- : null is not allowed 

2016-12-21 13:23:27,913 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2016-12-21 13:23:58,199 - knowledge_logger - main.py-parse-request : null is not allowed 

2016-12-21 13:23:58,199 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 802, in parse_structure
    request = parse_structure_VariantType_knowledgetransaction_Request(request)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/parse_structure.py", line 736, in parse_structure_VariantType_knowledgetransaction_Request
    return knowledgetransaction.Request.parse_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 34, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 59, in parse_inner_structure
    data = parse_dictionary(data, ["approval_status_id", "rcount"])
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 379, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 287, in parse_values
    val = parse_number(val, 0, _length)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 50, in parse_number
    raise empty_error()
ValueError: null is not allowed
 

2016-12-21 13:23:58,200 - knowledge_logger - main.py-handle-api- : null is not allowed 

2016-12-21 13:23:58,200 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2016-12-21 13:24:36,333 - knowledge_logger - main.py-parse-request : null is not allowed 

2016-12-21 13:24:36,333 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 802, in parse_structure
    request = parse_structure_VariantType_knowledgetransaction_Request(request)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/parse_structure.py", line 736, in parse_structure_VariantType_knowledgetransaction_Request
    return knowledgetransaction.Request.parse_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 34, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 59, in parse_inner_structure
    data = parse_dictionary(data, ["approval_status_id", "rcount"])
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 379, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 287, in parse_values
    val = parse_number(val, 0, _length)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 50, in parse_number
    raise empty_error()
ValueError: null is not allowed
 

2016-12-21 13:24:36,334 - knowledge_logger - main.py-handle-api- : null is not allowed 

2016-12-21 13:24:36,334 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2016-12-21 13:24:50,499 - knowledge_logger - main.py-parse-request : null is not allowed 

2016-12-21 13:24:50,500 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 802, in parse_structure
    request = parse_structure_VariantType_knowledgetransaction_Request(request)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/parse_structure.py", line 736, in parse_structure_VariantType_knowledgetransaction_Request
    return knowledgetransaction.Request.parse_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 34, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 59, in parse_inner_structure
    data = parse_dictionary(data, ["approval_status_id", "rcount"])
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 379, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 287, in parse_values
    val = parse_number(val, 0, _length)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 50, in parse_number
    raise empty_error()
ValueError: null is not allowed
 

2016-12-21 13:24:50,500 - knowledge_logger - main.py-handle-api- : null is not allowed 

2016-12-21 13:24:50,500 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2016-12-21 13:24:59,349 - knowledge_logger - main.py-parse-request : null is not allowed 

2016-12-21 13:24:59,349 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 802, in parse_structure
    request = parse_structure_VariantType_knowledgetransaction_Request(request)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/parse_structure.py", line 736, in parse_structure_VariantType_knowledgetransaction_Request
    return knowledgetransaction.Request.parse_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 34, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 59, in parse_inner_structure
    data = parse_dictionary(data, ["approval_status_id", "rcount"])
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 379, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 287, in parse_values
    val = parse_number(val, 0, _length)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 50, in parse_number
    raise empty_error()
ValueError: null is not allowed
 

2016-12-21 13:24:59,350 - knowledge_logger - main.py-handle-api- : null is not allowed 

2016-12-21 13:24:59,350 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2016-12-21 13:59:04,791 - knowledge_logger - main.py-parse-request : expected a number between 0 and 5, but received: -1 

2016-12-21 13:59:04,792 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 802, in parse_structure
    request = parse_structure_VariantType_knowledgetransaction_Request(request)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/parse_structure.py", line 736, in parse_structure_VariantType_knowledgetransaction_Request
    return knowledgetransaction.Request.parse_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 34, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 59, in parse_inner_structure
    data = parse_dictionary(data, ["approval_status_id", "rcount"])
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 379, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 287, in parse_values
    val = parse_number(val, 0, _length)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 60, in parse_number
    raise expectation_error(msg, x)
ValueError: expected a number between 0 and 5, but received: -1
 

2016-12-21 13:59:04,792 - knowledge_logger - main.py-handle-api- : expected a number between 0 and 5, but received: -1 

2016-12-21 13:59:04,792 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: expected a number between 0 and 5, but received: -1
 

2016-12-21 14:45:02,780 - knowledge_logger - main.py-parse-request : expected a number between 0 and 5, but received: -1 

2016-12-21 14:45:02,781 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 802, in parse_structure
    request = parse_structure_VariantType_knowledgetransaction_Request(request)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/parse_structure.py", line 736, in parse_structure_VariantType_knowledgetransaction_Request
    return knowledgetransaction.Request.parse_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 34, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 59, in parse_inner_structure
    data = parse_dictionary(data, ["approval_status_id", "rcount"])
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 379, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 287, in parse_values
    val = parse_number(val, 0, _length)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 60, in parse_number
    raise expectation_error(msg, x)
ValueError: expected a number between 0 and 5, but received: -1
 

2016-12-21 14:45:02,781 - knowledge_logger - main.py-handle-api- : expected a number between 0 and 5, but received: -1 

2016-12-21 14:45:02,781 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: expected a number between 0 and 5, but received: -1
 

2016-12-21 14:45:26,263 - knowledge_logger - main.py-parse-request : expected a number between 0 and 5, but received: 6 

2016-12-21 14:45:26,263 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 802, in parse_structure
    request = parse_structure_VariantType_knowledgetransaction_Request(request)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/parse_structure.py", line 736, in parse_structure_VariantType_knowledgetransaction_Request
    return knowledgetransaction.Request.parse_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 34, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 59, in parse_inner_structure
    data = parse_dictionary(data, ["approval_status_id", "rcount"])
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 379, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 287, in parse_values
    val = parse_number(val, 0, _length)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 60, in parse_number
    raise expectation_error(msg, x)
ValueError: expected a number between 0 and 5, but received: 6
 

2016-12-21 14:45:26,263 - knowledge_logger - main.py-handle-api- : expected a number between 0 and 5, but received: 6 

2016-12-21 14:45:26,263 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: expected a number between 0 and 5, but received: 6
 

2016-12-21 15:08:00,354 - knowledge_logger - main.py-handle-api- : expected a list, but received: ([<protocol.core.MappedCompliance object at 0x7fb6a081b150>, <protocol.core.MappedCompliance object at 0x7fb6a081b1d0>],) 

2016-12-21 15:08:00,355 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 214, in handle_api_request
    return respond(response_data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 180, in respond
    response_data, 200
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 135, in _send_response
    data = response_data.to_structure()
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 357, in to_structure
    inner = to_structure_dictionary_values(inner)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 422, in to_structure_dictionary_values
    _module_name, _class_name, val
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 513, in to_VectorType
    to_RecordType(module_name, class_name, item)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 495, in to_RecordType
    return to_structure_dictionary_values(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 422, in to_structure_dictionary_values
    _module_name, _class_name, val
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 509, in to_VectorType
    data = parse_list(data, 0)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 157, in parse_list
    raise expectation_error("a list", x)
ValueError: expected a list, but received: ([<protocol.core.MappedCompliance object at 0x7fb6a081b150>, <protocol.core.MappedCompliance object at 0x7fb6a081b1d0>],)
 

2016-12-21 15:09:03,755 - knowledge_logger - main.py-handle-api- : expected a list, but received: ([],) 

2016-12-21 15:09:03,755 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 214, in handle_api_request
    return respond(response_data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 180, in respond
    response_data, 200
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 135, in _send_response
    data = response_data.to_structure()
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 357, in to_structure
    inner = to_structure_dictionary_values(inner)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 422, in to_structure_dictionary_values
    _module_name, _class_name, val
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 513, in to_VectorType
    to_RecordType(module_name, class_name, item)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 495, in to_RecordType
    return to_structure_dictionary_values(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 422, in to_structure_dictionary_values
    _module_name, _class_name, val
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 509, in to_VectorType
    data = parse_list(data, 0)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 157, in parse_list
    raise expectation_error("a list", x)
ValueError: expected a list, but received: ([],)
 

2016-12-21 15:40:51,528 - knowledge_logger - main.py-parse-request : expected a dict, but received: False 

2016-12-21 15:40:51,529 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 802, in parse_structure
    request = parse_structure_VariantType_knowledgetransaction_Request(request)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/parse_structure.py", line 736, in parse_structure_VariantType_knowledgetransaction_Request
    return knowledgetransaction.Request.parse_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 34, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 127, in parse_inner_structure
    "compliances", "g_ids", "mappings", "tr_type"
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 181, in parse_dictionary
    raise expectation_error("a dict", x)
ValueError: expected a dict, but received: False
 

2016-12-21 15:40:51,529 - knowledge_logger - main.py-handle-api- : expected a dict, but received: False 

2016-12-21 15:40:51,529 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: expected a dict, but received: False
 

2016-12-21 15:52:06,097 - knowledge_logger - main.py-parse-request : expected a dict, but received: False 

2016-12-21 15:52:06,098 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 802, in parse_structure
    request = parse_structure_VariantType_knowledgetransaction_Request(request)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/parse_structure.py", line 736, in parse_structure_VariantType_knowledgetransaction_Request
    return knowledgetransaction.Request.parse_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 34, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 127, in parse_inner_structure
    "compliances", "g_ids", "mappings", "tr_type"
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 181, in parse_dictionary
    raise expectation_error("a dict", x)
ValueError: expected a dict, but received: False
 

2016-12-21 15:52:06,098 - knowledge_logger - main.py-handle-api- : expected a dict, but received: False 

2016-12-21 15:52:06,098 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: expected a dict, but received: False
 

2016-12-21 15:53:04,876 - knowledge_logger - main.py-parse-request : expected a dict, but received: False 

2016-12-21 15:53:04,876 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 802, in parse_structure
    request = parse_structure_VariantType_knowledgetransaction_Request(request)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/parse_structure.py", line 736, in parse_structure_VariantType_knowledgetransaction_Request
    return knowledgetransaction.Request.parse_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 34, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 127, in parse_inner_structure
    "compliances", "g_ids", "mappings", "tr_type"
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 181, in parse_dictionary
    raise expectation_error("a dict", x)
ValueError: expected a dict, but received: False
 

2016-12-21 15:53:04,876 - knowledge_logger - main.py-handle-api- : expected a dict, but received: False 

2016-12-21 15:53:04,876 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: expected a dict, but received: False
 

2016-12-21 15:53:16,936 - knowledge_logger - main.py-parse-request : null is not allowed 

2016-12-21 15:53:16,936 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 799, in parse_structure
    data = parse_dictionary(data, ["session_token", "request"])
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 379, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 280, in parse_values
    val = parse_string(val)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 79, in parse_string
    raise empty_error()
ValueError: null is not allowed
 

2016-12-21 15:53:16,936 - knowledge_logger - main.py-handle-api- : null is not allowed 

2016-12-21 15:53:16,936 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2016-12-21 15:53:16,944 - knowledge_logger - main.py-parse-request : null is not allowed 

2016-12-21 15:53:16,945 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 799, in parse_structure
    data = parse_dictionary(data, ["session_token", "request"])
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 379, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 280, in parse_values
    val = parse_string(val)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 79, in parse_string
    raise empty_error()
ValueError: null is not allowed
 

2016-12-21 15:53:16,945 - knowledge_logger - main.py-handle-api- : null is not allowed 

2016-12-21 15:53:16,945 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2016-12-21 15:53:16,954 - knowledge_logger - main.py-parse-request : null is not allowed 

2016-12-21 15:53:16,954 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 799, in parse_structure
    data = parse_dictionary(data, ["session_token", "request"])
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 379, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 280, in parse_values
    val = parse_string(val)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 79, in parse_string
    raise empty_error()
ValueError: null is not allowed
 

2016-12-21 15:53:16,954 - knowledge_logger - main.py-handle-api- : null is not allowed 

2016-12-21 15:53:16,954 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2016-12-21 15:54:32,843 - knowledge_logger - main.py-parse-request : expected a dict, but received: False 

2016-12-21 15:54:32,843 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 802, in parse_structure
    request = parse_structure_VariantType_knowledgetransaction_Request(request)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/parse_structure.py", line 736, in parse_structure_VariantType_knowledgetransaction_Request
    return knowledgetransaction.Request.parse_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 34, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 127, in parse_inner_structure
    "compliances", "g_ids", "mappings", "tr_type"
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 181, in parse_dictionary
    raise expectation_error("a dict", x)
ValueError: expected a dict, but received: False
 

2016-12-21 15:54:32,843 - knowledge_logger - main.py-handle-api- : expected a dict, but received: False 

2016-12-21 15:54:32,843 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: expected a dict, but received: False
 

2016-12-21 15:59:29,572 - knowledge_logger - main.py-parse-request : expected a dict, but received: False 

2016-12-21 15:59:29,572 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 802, in parse_structure
    request = parse_structure_VariantType_knowledgetransaction_Request(request)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/parse_structure.py", line 736, in parse_structure_VariantType_knowledgetransaction_Request
    return knowledgetransaction.Request.parse_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 34, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 127, in parse_inner_structure
    "compliances", "g_ids", "mappings", "tr_type"
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 181, in parse_dictionary
    raise expectation_error("a dict", x)
ValueError: expected a dict, but received: False
 

2016-12-21 15:59:29,573 - knowledge_logger - main.py-handle-api- : expected a dict, but received: False 

2016-12-21 15:59:29,573 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: expected a dict, but received: False
 

2016-12-21 16:01:26,341 - knowledge_logger - main.py-parse-request : expected a dict, but received: False 

2016-12-21 16:01:26,342 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 802, in parse_structure
    request = parse_structure_VariantType_knowledgetransaction_Request(request)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/parse_structure.py", line 736, in parse_structure_VariantType_knowledgetransaction_Request
    return knowledgetransaction.Request.parse_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 34, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 127, in parse_inner_structure
    "compliances", "g_ids", "mappings", "tr_type"
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 181, in parse_dictionary
    raise expectation_error("a dict", x)
ValueError: expected a dict, but received: False
 

2016-12-21 16:01:26,342 - knowledge_logger - main.py-handle-api- : expected a dict, but received: False 

2016-12-21 16:01:26,342 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: expected a dict, but received: False
 

2016-12-21 16:04:03,927 - knowledge_logger - main.py-parse-request : expected a dict, but received: False 

2016-12-21 16:04:03,928 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 802, in parse_structure
    request = parse_structure_VariantType_knowledgetransaction_Request(request)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/parse_structure.py", line 736, in parse_structure_VariantType_knowledgetransaction_Request
    return knowledgetransaction.Request.parse_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 34, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 127, in parse_inner_structure
    "compliances", "g_ids", "mappings", "tr_type"
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 181, in parse_dictionary
    raise expectation_error("a dict", x)
ValueError: expected a dict, but received: False
 

2016-12-21 16:04:03,928 - knowledge_logger - main.py-handle-api- : expected a dict, but received: False 

2016-12-21 16:04:03,928 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: expected a dict, but received: False
 

2016-12-21 16:12:46,511 - knowledge_logger - main.py-handle-api- : 'UpdateStatutory' object has no attribute 'parent_ids' 

2016-12-21 16:12:46,511 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 202, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 335, in handle_knowledge_master
    return controller.process_knowledge_master_request(request, db)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/controller/knowledgemastercontroller.py", line 161, in process_knowledge_master_request
    result = process_update_statutory(db, request_frame, user_id)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/controller/knowledgemastercontroller.py", line 489, in process_update_statutory
    parent_ids_list = request_frame.parent_ids
AttributeError: 'UpdateStatutory' object has no attribute 'parent_ids'
 

2016-12-21 16:12:59,330 - knowledge_logger - main.py-handle-api- : 'UpdateStatutory' object has no attribute 'parent_ids' 

2016-12-21 16:12:59,330 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 202, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 335, in handle_knowledge_master
    return controller.process_knowledge_master_request(request, db)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/controller/knowledgemastercontroller.py", line 161, in process_knowledge_master_request
    result = process_update_statutory(db, request_frame, user_id)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/controller/knowledgemastercontroller.py", line 489, in process_update_statutory
    parent_ids_list = request_frame.parent_ids
AttributeError: 'UpdateStatutory' object has no attribute 'parent_ids'
 

2016-12-21 16:52:47,516 - knowledge_logger - main.py-handle-api- : global name 'parent_ids' is not defined 

2016-12-21 16:52:47,516 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 202, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 335, in handle_knowledge_master
    return controller.process_knowledge_master_request(request, db)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/controller/knowledgemastercontroller.py", line 161, in process_knowledge_master_request
    result = process_update_statutory(db, request_frame, user_id)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/controller/knowledgemastercontroller.py", line 494, in process_update_statutory
    db, parent_ids, statutory_id)
NameError: global name 'parent_ids' is not defined
 

2016-12-21 16:54:15,942 - knowledge_logger - main.py-handle-api- : 'UpdateStatutory' object has no attribute 'parent_ids' 

2016-12-21 16:54:15,942 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 202, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 335, in handle_knowledge_master
    return controller.process_knowledge_master_request(request, db)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/controller/knowledgemastercontroller.py", line 161, in process_knowledge_master_request
    result = process_update_statutory(db, request_frame, user_id)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/controller/knowledgemastercontroller.py", line 489, in process_update_statutory
    parent_ids_list = request_frame.parent_ids
AttributeError: 'UpdateStatutory' object has no attribute 'parent_ids'
 

2016-12-21 16:54:32,384 - knowledge_logger - main.py-handle-api- : global name 'parent_ids' is not defined 

2016-12-21 16:54:32,384 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 202, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 335, in handle_knowledge_master
    return controller.process_knowledge_master_request(request, db)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/controller/knowledgemastercontroller.py", line 154, in process_knowledge_master_request
    result = process_save_statutory(db, request_frame, user_id)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/controller/knowledgemastercontroller.py", line 472, in process_save_statutory
    db, parent_ids, statutory_id, domain_id
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/database/knowledgemaster.py", line 825, in check_duplicate_statutory
    param = [parent_ids]
NameError: global name 'parent_ids' is not defined
 

2016-12-21 16:55:30,702 - knowledge_logger - main.py-handle-api- : 'UpdateStatutory' object has no attribute 'parent_ids' 

2016-12-21 16:55:30,702 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 202, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 335, in handle_knowledge_master
    return controller.process_knowledge_master_request(request, db)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/controller/knowledgemastercontroller.py", line 161, in process_knowledge_master_request
    result = process_update_statutory(db, request_frame, user_id)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/controller/knowledgemastercontroller.py", line 489, in process_update_statutory
    parent_ids_list = request_frame.parent_ids
AttributeError: 'UpdateStatutory' object has no attribute 'parent_ids'
 

2016-12-21 16:59:17,182 - knowledge_logger - main.py-handle-api- : update_statutory() takes exactly 4 arguments (6 given) 

2016-12-21 16:59:17,183 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 202, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 335, in handle_knowledge_master
    return controller.process_knowledge_master_request(request, db)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/controller/knowledgemastercontroller.py", line 161, in process_knowledge_master_request
    result = process_update_statutory(db, request_frame, user_id)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/controller/knowledgemastercontroller.py", line 505, in process_update_statutory
    parent_names, user_id
TypeError: update_statutory() takes exactly 4 arguments (6 given)
 

2016-12-21 17:00:53,684 - knowledge_logger - main.py-handle-api- :  

2016-12-21 17:00:53,684 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 202, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 335, in handle_knowledge_master
    return controller.process_knowledge_master_request(request, db)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/controller/knowledgemastercontroller.py", line 161, in process_knowledge_master_request
    result = process_update_statutory(db, request_frame, user_id)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/controller/knowledgemastercontroller.py", line 505, in process_update_statutory
    user_id
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/database/knowledgemaster.py", line 685, in update_statutory
    oldData = get_statutory_by_id(db, statutory_id)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/database/knowledgemaster.py", line 657, in get_statutory_by_id
    result = convert_to_dict(rows, columns)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/common.py", line 104, in convert_to_dict
    assert type(data_list) in (list, tuple)
AssertionError
 

2016-12-21 17:02:02,501 - knowledge_logger - main.py-handle-api- :  

2016-12-21 17:02:02,502 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 202, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 335, in handle_knowledge_master
    return controller.process_knowledge_master_request(request, db)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/controller/knowledgemastercontroller.py", line 161, in process_knowledge_master_request
    result = process_update_statutory(db, request_frame, user_id)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/controller/knowledgemastercontroller.py", line 505, in process_update_statutory
    user_id
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/database/knowledgemaster.py", line 685, in update_statutory
    oldData = get_statutory_by_id(db, statutory_id)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/database/knowledgemaster.py", line 657, in get_statutory_by_id
    result = convert_to_dict(rows, columns)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/common.py", line 104, in convert_to_dict
    assert type(data_list) in (list, tuple)
AssertionError
 

2016-12-21 17:37:27,119 - knowledge_logger - main.py-parse-request : expected a alphanumerics, but received: Pay Section !A 

2016-12-21 17:37:27,120 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgemaster.py", line 972, in parse_structure
    request = parse_structure_VariantType_knowledgemaster_Request(request)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/parse_structure.py", line 107, in parse_structure_VariantType_knowledgemaster_Request
    return knowledgemaster.Request.parse_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgemaster.py", line 33, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgemaster.py", line 393, in parse_inner_structure
    "d_id", "s_l_id", "s_name", "s_pids", "s_pnames"
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 385, in parse_dictionary_values
    val = _validation_method(val)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/api_key_validation.py", line 37, in is_alpha_numeric
    raise expectation_error('a alphanumerics', value)
ValueError: expected a alphanumerics, but received: Pay Section !A
 

2016-12-21 17:37:27,120 - knowledge_logger - main.py-handle-api- : expected a alphanumerics, but received: Pay Section !A 

2016-12-21 17:37:27,121 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: expected a alphanumerics, but received: Pay Section !A
 

2016-12-21 18:05:47,332 - knowledge_logger - main.py-parse-request : expected key "m_id" is missing in the dictionary, but received: {u'c_id': 1, u'mappings': [u'Bonus Act 2016>>Bonus old Section'], u's_ids': [25], u'tr_type': 0, u'd_id': 1, u'g_ids': [5], u'i_ids': [1], u's_n_id': 1, u'compliances': [{u'comp_id': None, u'c_task': u'One time task', u'd_type_id': None, u'description': u'dsdf', u'reference': u'', u'is_active': True, u'f_id': 1, u'f_f_list': None, u'r_every': None, u'summary': None, u'doc_name': u'', u'statu_dates': [{u'statutory_month': None, u'statutory_date': None, u'trigger_before_days': 15, u'repeat_by': None}], u'frequency': u'One Time', u'duration': None, u'r_type_id': None, u's_provision': u's Prob', u'p_consequences': u''}]} 

2016-12-21 18:05:47,332 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 802, in parse_structure
    request = parse_structure_VariantType_knowledgetransaction_Request(request)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/parse_structure.py", line 736, in parse_structure_VariantType_knowledgetransaction_Request
    return knowledgetransaction.Request.parse_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 34, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 180, in parse_inner_structure
    "compliances", "g_ids", "mappings", "tr_type"
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 187, in parse_dictionary
    raise expectation_error(msg, x)
ValueError: expected key "m_id" is missing in the dictionary, but received: {u'c_id': 1, u'mappings': [u'Bonus Act 2016>>Bonus old Section'], u's_ids': [25], u'tr_type': 0, u'd_id': 1, u'g_ids': [5], u'i_ids': [1], u's_n_id': 1, u'compliances': [{u'comp_id': None, u'c_task': u'One time task', u'd_type_id': None, u'description': u'dsdf', u'reference': u'', u'is_active': True, u'f_id': 1, u'f_f_list': None, u'r_every': None, u'summary': None, u'doc_name': u'', u'statu_dates': [{u'statutory_month': None, u'statutory_date': None, u'trigger_before_days': 15, u'repeat_by': None}], u'frequency': u'One Time', u'duration': None, u'r_type_id': None, u's_provision': u's Prob', u'p_consequences': u''}]}
 

2016-12-21 18:05:47,333 - knowledge_logger - main.py-handle-api- : expected key "m_id" is missing in the dictionary, but received: {u'c_id': 1, u'mappings': [u'Bonus Act 2016>>Bonus old Section'], u's_ids': [25], u'tr_type': 0, u'd_id': 1, u'g_ids': [5], u'i_ids': [1], u's_n_id': 1, u'compliances': [{u'comp_id': None, u'c_task': u'One time task', u'd_type_id': None, u'description': u'dsdf', u'reference': u'', u'is_active': True, u'f_id': 1, u'f_f_list': None, u'r_every': None, u'summary': None, u'doc_name': u'', u'statu_dates': [{u'statutory_month': None, u'statutory_date': None, u'trigger_before_days': 15, u'repeat_by': None}], u'frequency': u'One Time', u'duration': None, u'r_type_id': None, u's_provision': u's Prob', u'p_consequences': u''}]} 

2016-12-21 18:05:47,333 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: expected key "m_id" is missing in the dictionary, but received: {u'c_id': 1, u'mappings': [u'Bonus Act 2016>>Bonus old Section'], u's_ids': [25], u'tr_type': 0, u'd_id': 1, u'g_ids': [5], u'i_ids': [1], u's_n_id': 1, u'compliances': [{u'comp_id': None, u'c_task': u'One time task', u'd_type_id': None, u'description': u'dsdf', u'reference': u'', u'is_active': True, u'f_id': 1, u'f_f_list': None, u'r_every': None, u'summary': None, u'doc_name': u'', u'statu_dates': [{u'statutory_month': None, u'statutory_date': None, u'trigger_before_days': 15, u'repeat_by': None}], u'frequency': u'One Time', u'duration': None, u'r_type_id': None, u's_provision': u's Prob', u'p_consequences': u''}]}
 

2016-12-21 18:06:02,227 - knowledge_logger - main.py-parse-request : expected key "m_id" is missing in the dictionary, but received: {u'c_id': 1, u'mappings': [u'Bonus Act 2016>>Bonus old Section'], u's_ids': [25], u'tr_type': 0, u'd_id': 1, u'g_ids': [5], u'i_ids': [1], u's_n_id': 1, u'compliances': [{u'comp_id': None, u'c_task': u'One time task', u'd_type_id': None, u'description': u'dsdf', u'reference': u'', u'is_active': True, u'f_id': 1, u'f_f_list': None, u'r_every': None, u'summary': None, u'doc_name': u'', u'statu_dates': [{u'statutory_month': None, u'statutory_date': None, u'trigger_before_days': 15, u'repeat_by': None}], u'frequency': u'One Time', u'duration': None, u'r_type_id': None, u's_provision': u's Prob', u'p_consequences': u''}]} 

2016-12-21 18:06:02,227 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 802, in parse_structure
    request = parse_structure_VariantType_knowledgetransaction_Request(request)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/parse_structure.py", line 736, in parse_structure_VariantType_knowledgetransaction_Request
    return knowledgetransaction.Request.parse_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 34, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 180, in parse_inner_structure
    "compliances", "g_ids", "mappings", "tr_type"
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 187, in parse_dictionary
    raise expectation_error(msg, x)
ValueError: expected key "m_id" is missing in the dictionary, but received: {u'c_id': 1, u'mappings': [u'Bonus Act 2016>>Bonus old Section'], u's_ids': [25], u'tr_type': 0, u'd_id': 1, u'g_ids': [5], u'i_ids': [1], u's_n_id': 1, u'compliances': [{u'comp_id': None, u'c_task': u'One time task', u'd_type_id': None, u'description': u'dsdf', u'reference': u'', u'is_active': True, u'f_id': 1, u'f_f_list': None, u'r_every': None, u'summary': None, u'doc_name': u'', u'statu_dates': [{u'statutory_month': None, u'statutory_date': None, u'trigger_before_days': 15, u'repeat_by': None}], u'frequency': u'One Time', u'duration': None, u'r_type_id': None, u's_provision': u's Prob', u'p_consequences': u''}]}
 

2016-12-21 18:06:02,228 - knowledge_logger - main.py-handle-api- : expected key "m_id" is missing in the dictionary, but received: {u'c_id': 1, u'mappings': [u'Bonus Act 2016>>Bonus old Section'], u's_ids': [25], u'tr_type': 0, u'd_id': 1, u'g_ids': [5], u'i_ids': [1], u's_n_id': 1, u'compliances': [{u'comp_id': None, u'c_task': u'One time task', u'd_type_id': None, u'description': u'dsdf', u'reference': u'', u'is_active': True, u'f_id': 1, u'f_f_list': None, u'r_every': None, u'summary': None, u'doc_name': u'', u'statu_dates': [{u'statutory_month': None, u'statutory_date': None, u'trigger_before_days': 15, u'repeat_by': None}], u'frequency': u'One Time', u'duration': None, u'r_type_id': None, u's_provision': u's Prob', u'p_consequences': u''}]} 

2016-12-21 18:06:02,228 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: expected key "m_id" is missing in the dictionary, but received: {u'c_id': 1, u'mappings': [u'Bonus Act 2016>>Bonus old Section'], u's_ids': [25], u'tr_type': 0, u'd_id': 1, u'g_ids': [5], u'i_ids': [1], u's_n_id': 1, u'compliances': [{u'comp_id': None, u'c_task': u'One time task', u'd_type_id': None, u'description': u'dsdf', u'reference': u'', u'is_active': True, u'f_id': 1, u'f_f_list': None, u'r_every': None, u'summary': None, u'doc_name': u'', u'statu_dates': [{u'statutory_month': None, u'statutory_date': None, u'trigger_before_days': 15, u'repeat_by': None}], u'frequency': u'One Time', u'duration': None, u'r_type_id': None, u's_provision': u's Prob', u'p_consequences': u''}]}
 

2016-12-21 18:07:01,861 - knowledge_logger - main.py-parse-request : expected key "m_id" is missing in the dictionary, but received: {u'c_id': 1, u'mappings': [u'Bonus Act 2016>>Bonus old Section'], u's_ids': [25], u'tr_type': 0, u'd_id': 1, u'g_ids': [5], u'i_ids': [1], u's_n_id': 1, u'compliances': [{u'comp_id': None, u'c_task': u'c task one time', u'd_type_id': None, u'description': u'ssdfsdf', u'reference': u'', u'is_active': True, u'f_id': 1, u'f_f_list': None, u'r_every': None, u'summary': None, u'doc_name': u'', u'statu_dates': [{u'statutory_month': None, u'statutory_date': None, u'trigger_before_days': 15, u'repeat_by': None}], u'frequency': u'One Time', u'duration': None, u'r_type_id': None, u's_provision': u's prov', u'p_consequences': u''}]} 

2016-12-21 18:07:01,861 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 155, in _parse_request
    data
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 802, in parse_structure
    request = parse_structure_VariantType_knowledgetransaction_Request(request)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/parse_structure.py", line 736, in parse_structure_VariantType_knowledgetransaction_Request
    return knowledgetransaction.Request.parse_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 34, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/knowledgetransaction.py", line 180, in parse_inner_structure
    "compliances", "g_ids", "mappings", "tr_type"
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/protocol/jsonvalidators.py", line 187, in parse_dictionary
    raise expectation_error(msg, x)
ValueError: expected key "m_id" is missing in the dictionary, but received: {u'c_id': 1, u'mappings': [u'Bonus Act 2016>>Bonus old Section'], u's_ids': [25], u'tr_type': 0, u'd_id': 1, u'g_ids': [5], u'i_ids': [1], u's_n_id': 1, u'compliances': [{u'comp_id': None, u'c_task': u'c task one time', u'd_type_id': None, u'description': u'ssdfsdf', u'reference': u'', u'is_active': True, u'f_id': 1, u'f_f_list': None, u'r_every': None, u'summary': None, u'doc_name': u'', u'statu_dates': [{u'statutory_month': None, u'statutory_date': None, u'trigger_before_days': 15, u'repeat_by': None}], u'frequency': u'One Time', u'duration': None, u'r_type_id': None, u's_provision': u's prov', u'p_consequences': u''}]}
 

2016-12-21 18:07:01,861 - knowledge_logger - main.py-handle-api- : expected key "m_id" is missing in the dictionary, but received: {u'c_id': 1, u'mappings': [u'Bonus Act 2016>>Bonus old Section'], u's_ids': [25], u'tr_type': 0, u'd_id': 1, u'g_ids': [5], u'i_ids': [1], u's_n_id': 1, u'compliances': [{u'comp_id': None, u'c_task': u'c task one time', u'd_type_id': None, u'description': u'ssdfsdf', u'reference': u'', u'is_active': True, u'f_id': 1, u'f_f_list': None, u'r_every': None, u'summary': None, u'doc_name': u'', u'statu_dates': [{u'statutory_month': None, u'statutory_date': None, u'trigger_before_days': 15, u'repeat_by': None}], u'frequency': u'One Time', u'duration': None, u'r_type_id': None, u's_provision': u's prov', u'p_consequences': u''}]} 

2016-12-21 18:07:01,861 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 196, in handle_api_request
    raise ValueError(request_data)
ValueError: expected key "m_id" is missing in the dictionary, but received: {u'c_id': 1, u'mappings': [u'Bonus Act 2016>>Bonus old Section'], u's_ids': [25], u'tr_type': 0, u'd_id': 1, u'g_ids': [5], u'i_ids': [1], u's_n_id': 1, u'compliances': [{u'comp_id': None, u'c_task': u'c task one time', u'd_type_id': None, u'description': u'ssdfsdf', u'reference': u'', u'is_active': True, u'f_id': 1, u'f_f_list': None, u'r_every': None, u'summary': None, u'doc_name': u'', u'statu_dates': [{u'statutory_month': None, u'statutory_date': None, u'trigger_before_days': 15, u'repeat_by': None}], u'frequency': u'One Time', u'duration': None, u'r_type_id': None, u's_provision': u's prov', u'p_consequences': u''}]}
 

2016-12-21 19:01:33,625 - knowledge_logger - main.py-handle-api- : 'SaveStatutoryMapping' object has no attribute 'mapping_id' 

2016-12-21 19:01:33,625 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 202, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 339, in handle_knowledge_transaction
    return controller.process_knowledge_transaction_request(request, db)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/controller/knowledgetransactioncontroller.py", line 72, in process_knowledge_transaction_request
    result = process_save_statutory_mapping(db, request_frame, user_id)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/controller/knowledgetransactioncontroller.py", line 147, in process_save_statutory_mapping
    if request_frame.mapping_id is not None :
AttributeError: 'SaveStatutoryMapping' object has no attribute 'mapping_id'
 

2016-12-21 19:27:20,491 - knowledge_logger - main.py-handle-api- : 'duration_type' 

2016-12-21 19:27:20,492 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 202, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 339, in handle_knowledge_transaction
    return controller.process_knowledge_transaction_request(request, db)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/controller/knowledgetransactioncontroller.py", line 103, in process_knowledge_transaction_request
    result = process_get_compliance_info(db, request_frame, user_id)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/controller/knowledgetransactioncontroller.py", line 192, in process_get_compliance_info
    comp_info = get_compliance_details(db, user_id, comp_id)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/database/knowledgetransaction.py", line 1376, in get_compliance_details
    summary = make_summary(date_list, c_info["frequency_id"], c_info)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/common.py", line 358, in make_summary
    c["duration"], c["duration_type"]
KeyError: 'duration_type'
 

2016-12-21 19:27:22,508 - knowledge_logger - main.py-handle-api- : 'duration_type' 

2016-12-21 19:27:22,509 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 202, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/main.py", line 339, in handle_knowledge_transaction
    return controller.process_knowledge_transaction_request(request, db)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/controller/knowledgetransactioncontroller.py", line 103, in process_knowledge_transaction_request
    result = process_get_compliance_info(db, request_frame, user_id)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/controller/knowledgetransactioncontroller.py", line 192, in process_get_compliance_info
    comp_info = get_compliance_details(db, user_id, comp_id)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/database/knowledgetransaction.py", line 1376, in get_compliance_details
    summary = make_summary(date_list, c_info["frequency_id"], c_info)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Src-server/server/common.py", line 358, in make_summary
    c["duration"], c["duration_type"]
KeyError: 'duration_type'
 

