2016-12-23 11:18:41,610 - client_logger - exception : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 141, in server_added
    company.db_name
TypeError: __init__() takes exactly 2 arguments (6 given)
 

2016-12-23 11:18:41,611 - client_logger - clientmain.py-server-added : __init__() takes exactly 2 arguments (6 given) 

2016-12-23 11:18:41,611 - client_logger - clientmain.py-server-added : unsupported operand type(s) for +: 'int' and 'str' 

2016-12-23 11:18:41,611 - client_logger - clientmain.py-server-added : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 154, in server_added
    logger.logClientApi("Client database not available to connect ", company_id + "-" + company.to_structure())
TypeError: unsupported operand type(s) for +: 'int' and 'str'
 

2016-12-23 11:20:21,727 - client_logger - exception : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 141, in server_added
    company.db_name
TypeError: __init__() takes exactly 2 arguments (6 given)
 

2016-12-23 11:20:21,728 - client_logger - clientmain.py-server-added : __init__() takes exactly 2 arguments (6 given) 

2016-12-23 11:20:21,729 - client_logger - clientmain.py-server-added : unsupported operand type(s) for +: 'int' and 'str' 

2016-12-23 11:20:21,729 - client_logger - clientmain.py-server-added : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 154, in server_added
    logger.logClientApi("Client database not available to connect ", company_id + "-" + company.to_structure())
TypeError: unsupported operand type(s) for +: 'int' and 'str'
 

2016-12-23 11:22:01,841 - client_logger - exception : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 141, in server_added
    company.db_name
TypeError: __init__() takes exactly 2 arguments (6 given)
 

2016-12-23 11:22:01,842 - client_logger - clientmain.py-server-added : __init__() takes exactly 2 arguments (6 given) 

2016-12-23 11:22:01,842 - client_logger - clientmain.py-server-added : unsupported operand type(s) for +: 'int' and 'str' 

2016-12-23 11:22:01,843 - client_logger - clientmain.py-server-added : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 154, in server_added
    logger.logClientApi("Client database not available to connect ", company_id + "-" + company.to_structure())
TypeError: unsupported operand type(s) for +: 'int' and 'str'
 

2016-12-23 11:23:42,414 - client_logger - exception : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 141, in server_added
    company.db_name
TypeError: __init__() takes exactly 2 arguments (6 given)
 

2016-12-23 11:23:42,414 - client_logger - clientmain.py-server-added : __init__() takes exactly 2 arguments (6 given) 

2016-12-23 11:23:42,415 - client_logger - clientmain.py-server-added : unsupported operand type(s) for +: 'int' and 'str' 

2016-12-23 11:23:42,415 - client_logger - clientmain.py-server-added : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 154, in server_added
    logger.logClientApi("Client database not available to connect ", company_id + "-" + company.to_structure())
TypeError: unsupported operand type(s) for +: 'int' and 'str'
 

2016-12-23 11:25:22,444 - client_logger - exception : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 141, in server_added
    company.db_name
TypeError: __init__() takes exactly 2 arguments (6 given)
 

2016-12-23 11:25:22,445 - client_logger - clientmain.py-server-added : __init__() takes exactly 2 arguments (6 given) 

2016-12-23 11:25:22,446 - client_logger - clientmain.py-server-added : unsupported operand type(s) for +: 'int' and 'str' 

2016-12-23 11:25:22,446 - client_logger - clientmain.py-server-added : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 154, in server_added
    logger.logClientApi("Client database not available to connect ", company_id + "-" + company.to_structure())
TypeError: unsupported operand type(s) for +: 'int' and 'str'
 

2016-12-23 11:27:02,555 - client_logger - exception : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 141, in server_added
    self._databases = {}
TypeError: __init__() takes exactly 2 arguments (6 given)
 

2016-12-23 11:27:02,556 - client_logger - clientmain.py-server-added : __init__() takes exactly 2 arguments (6 given) 

2016-12-23 11:27:02,557 - client_logger - clientmain.py-server-added : unsupported operand type(s) for +: 'int' and 'str' 

2016-12-23 11:27:02,557 - client_logger - clientmain.py-server-added : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 154, in server_added
    company.db_ip.port,
TypeError: unsupported operand type(s) for +: 'int' and 'str'
 

2016-12-23 11:28:42,670 - client_logger - exception : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 141, in server_added
    self._databases = {}
TypeError: __init__() takes exactly 2 arguments (6 given)
 

2016-12-23 11:28:42,671 - client_logger - clientmain.py-server-added : __init__() takes exactly 2 arguments (6 given) 

2016-12-23 11:28:42,672 - client_logger - clientmain.py-server-added : unsupported operand type(s) for +: 'int' and 'str' 

2016-12-23 11:28:42,672 - client_logger - clientmain.py-server-added : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 154, in server_added
    #     company.db_ip.ip_address,
TypeError: unsupported operand type(s) for +: 'int' and 'str'
 

2016-12-23 11:30:22,780 - client_logger - exception : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 141, in server_added
    rep_man.stop()
TypeError: __init__() takes exactly 2 arguments (6 given)
 

2016-12-23 11:30:22,780 - client_logger - clientmain.py-server-added : __init__() takes exactly 2 arguments (6 given) 

2016-12-23 11:30:22,781 - client_logger - clientmain.py-server-added : unsupported operand type(s) for +: 'int' and 'str' 

2016-12-23 11:30:22,782 - client_logger - clientmain.py-server-added : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 154, in server_added
    db_cons = self.client_connection_pool(company, company_id)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
 

2016-12-23 11:32:02,888 - client_logger - exception : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 141, in server_added
    rep_man.stop()
TypeError: __init__() takes exactly 2 arguments (6 given)
 

2016-12-23 11:32:02,888 - client_logger - clientmain.py-server-added : __init__() takes exactly 2 arguments (6 given) 

2016-12-23 11:32:02,889 - client_logger - clientmain.py-server-added : unsupported operand type(s) for +: 'int' and 'str' 

2016-12-23 11:32:02,890 - client_logger - clientmain.py-server-added : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 154, in server_added
    db_cons = self.client_connection_pool(company, company_id)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
 

2016-12-23 11:33:42,959 - client_logger - exception : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 141, in server_added
    rep_man.stop()
TypeError: __init__() takes exactly 2 arguments (6 given)
 

2016-12-23 11:33:42,960 - client_logger - clientmain.py-server-added : __init__() takes exactly 2 arguments (6 given) 

2016-12-23 11:33:42,961 - client_logger - clientmain.py-server-added : unsupported operand type(s) for +: 'int' and 'str' 

2016-12-23 11:33:42,961 - client_logger - clientmain.py-server-added : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 154, in server_added
    db_cons = self.client_connection_pool(company, company_id)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
 

2016-12-23 11:35:23,062 - client_logger - exception : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 141, in server_added
    rep_man.stop()
TypeError: __init__() takes exactly 2 arguments (6 given)
 

2016-12-23 11:35:23,062 - client_logger - clientmain.py-server-added : __init__() takes exactly 2 arguments (6 given) 

2016-12-23 11:35:23,063 - client_logger - clientmain.py-server-added : unsupported operand type(s) for +: 'int' and 'str' 

2016-12-23 11:35:23,063 - client_logger - clientmain.py-server-added : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 154, in server_added
    db_cons = self.client_connection_pool(company, company_id)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
 

2016-12-23 11:37:03,094 - client_logger - exception : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 141, in server_added
    rep_man.stop()
TypeError: __init__() takes exactly 2 arguments (6 given)
 

2016-12-23 11:37:03,094 - client_logger - clientmain.py-server-added : __init__() takes exactly 2 arguments (6 given) 

2016-12-23 11:37:03,095 - client_logger - clientmain.py-server-added : unsupported operand type(s) for +: 'int' and 'str' 

2016-12-23 11:37:03,095 - client_logger - clientmain.py-server-added : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 154, in server_added
    db_cons = self.client_connection_pool(company, company_id)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
 

2016-12-23 11:38:43,210 - client_logger - exception : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 141, in server_added
    rep_man.stop()
TypeError: __init__() takes exactly 2 arguments (6 given)
 

2016-12-23 11:38:43,211 - client_logger - clientmain.py-server-added : __init__() takes exactly 2 arguments (6 given) 

2016-12-23 11:38:43,212 - client_logger - clientmain.py-server-added : unsupported operand type(s) for +: 'int' and 'str' 

2016-12-23 11:38:43,212 - client_logger - clientmain.py-server-added : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 154, in server_added
    db_cons = self.client_connection_pool(company, company_id)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
 

2016-12-23 11:40:23,277 - client_logger - exception : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 141, in server_added
    rep_man.stop()
TypeError: __init__() takes exactly 2 arguments (6 given)
 

2016-12-23 11:40:23,278 - client_logger - clientmain.py-server-added : __init__() takes exactly 2 arguments (6 given) 

2016-12-23 11:40:23,279 - client_logger - clientmain.py-server-added : unsupported operand type(s) for +: 'int' and 'str' 

2016-12-23 11:40:23,279 - client_logger - clientmain.py-server-added : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 154, in server_added
    db_cons = self.client_connection_pool(company, company_id)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
 

2016-12-23 11:42:03,338 - client_logger - exception : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 141, in server_added
    rep_man.stop()
TypeError: __init__() takes exactly 2 arguments (6 given)
 

2016-12-23 11:42:03,338 - client_logger - clientmain.py-server-added : __init__() takes exactly 2 arguments (6 given) 

2016-12-23 11:42:03,339 - client_logger - clientmain.py-server-added : unsupported operand type(s) for +: 'int' and 'str' 

2016-12-23 11:42:03,340 - client_logger - clientmain.py-server-added : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 154, in server_added
    db_cons = self.client_connection_pool(company, company_id)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
 

2016-12-23 11:43:43,442 - client_logger - exception : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 141, in server_added
    rep_man.stop()
TypeError: __init__() takes exactly 2 arguments (6 given)
 

2016-12-23 11:43:43,443 - client_logger - clientmain.py-server-added : __init__() takes exactly 2 arguments (6 given) 

2016-12-23 11:43:43,444 - client_logger - clientmain.py-server-added : unsupported operand type(s) for +: 'int' and 'str' 

2016-12-23 11:43:43,444 - client_logger - clientmain.py-server-added : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 154, in server_added
    db_cons = self.client_connection_pool(company, company_id)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
 

2016-12-23 11:45:23,549 - client_logger - exception : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 141, in server_added
    rep_man.stop()
TypeError: __init__() takes exactly 2 arguments (6 given)
 

2016-12-23 11:45:23,550 - client_logger - clientmain.py-server-added : __init__() takes exactly 2 arguments (6 given) 

2016-12-23 11:45:23,551 - client_logger - clientmain.py-server-added : unsupported operand type(s) for +: 'int' and 'str' 

2016-12-23 11:45:23,551 - client_logger - clientmain.py-server-added : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 154, in server_added
    db_cons = self.client_connection_pool(company, company_id)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
 

2016-12-23 11:47:03,654 - client_logger - exception : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 141, in server_added
    rep_man.stop()
TypeError: __init__() takes exactly 2 arguments (6 given)
 

2016-12-23 11:47:03,654 - client_logger - clientmain.py-server-added : __init__() takes exactly 2 arguments (6 given) 

2016-12-23 11:47:03,655 - client_logger - clientmain.py-server-added : unsupported operand type(s) for +: 'int' and 'str' 

2016-12-23 11:47:03,656 - client_logger - clientmain.py-server-added : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 154, in server_added
    db_cons = self.client_connection_pool(company, company_id)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
 

2016-12-23 11:48:43,732 - client_logger - exception : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 141, in server_added
    rep_man.stop()
TypeError: __init__() takes exactly 2 arguments (6 given)
 

2016-12-23 11:48:43,733 - client_logger - clientmain.py-server-added : __init__() takes exactly 2 arguments (6 given) 

2016-12-23 11:48:43,733 - client_logger - clientmain.py-server-added : unsupported operand type(s) for +: 'int' and 'str' 

2016-12-23 11:48:43,733 - client_logger - clientmain.py-server-added : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 154, in server_added
    db_cons = self.client_connection_pool(company, company_id)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
 

2016-12-23 11:50:23,827 - client_logger - exception : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 141, in server_added
    rep_man.stop()
TypeError: __init__() takes exactly 2 arguments (6 given)
 

2016-12-23 11:50:23,828 - client_logger - clientmain.py-server-added : __init__() takes exactly 2 arguments (6 given) 

2016-12-23 11:50:23,829 - client_logger - clientmain.py-server-added : unsupported operand type(s) for +: 'int' and 'str' 

2016-12-23 11:50:23,830 - client_logger - clientmain.py-server-added : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 154, in server_added
    db_cons = self.client_connection_pool(company, company_id)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
 

2016-12-23 11:52:03,862 - client_logger - exception : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 141, in server_added
    rep_man.stop()
TypeError: __init__() takes exactly 2 arguments (6 given)
 

2016-12-23 11:52:03,863 - client_logger - clientmain.py-server-added : __init__() takes exactly 2 arguments (6 given) 

2016-12-23 11:52:03,864 - client_logger - clientmain.py-server-added : unsupported operand type(s) for +: 'int' and 'str' 

2016-12-23 11:52:03,864 - client_logger - clientmain.py-server-added : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 154, in server_added
    db_cons = self.client_connection_pool(company, company_id)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
 

2016-12-23 11:53:43,972 - client_logger - exception : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 141, in server_added
    rep_man.stop()
TypeError: __init__() takes exactly 2 arguments (6 given)
 

2016-12-23 11:53:43,972 - client_logger - clientmain.py-server-added : __init__() takes exactly 2 arguments (6 given) 

2016-12-23 11:53:43,972 - client_logger - clientmain.py-server-added : unsupported operand type(s) for +: 'int' and 'str' 

2016-12-23 11:53:43,973 - client_logger - clientmain.py-server-added : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 154, in server_added
    db_cons = self.client_connection_pool(company, company_id)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
 

2016-12-23 11:55:24,019 - client_logger - exception : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 141, in server_added
    rep_man.stop()
TypeError: __init__() takes exactly 2 arguments (6 given)
 

2016-12-23 11:55:24,021 - client_logger - clientmain.py-server-added : __init__() takes exactly 2 arguments (6 given) 

2016-12-23 11:55:24,022 - client_logger - clientmain.py-server-added : unsupported operand type(s) for +: 'int' and 'str' 

2016-12-23 11:55:24,023 - client_logger - clientmain.py-server-added : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 154, in server_added
    db_cons = self.client_connection_pool(company, company_id)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
 

2016-12-23 12:26:58,123 - client_logger - exception : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 154, in server_added
    db_cons = self.client_connection_pool(company, company_id)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 121, in client_connection_pool
    pool_name=le_id + "con_pool",
TypeError: unsupported operand type(s) for +: 'int' and 'str'
 

2016-12-23 12:26:58,123 - client_logger - clientmain.py-server-added : unsupported operand type(s) for +: 'int' and 'str' 

2016-12-23 12:26:58,123 - client_logger - clientmain.py-server-added : unsupported operand type(s) for +: 'int' and 'str' 

2016-12-23 12:26:58,123 - client_logger - clientmain.py-server-added : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 174, in server_added
    logger.logClientApi("Client database not available to connect ", company_id + "-" + company.to_structure())
TypeError: unsupported operand type(s) for +: 'int' and 'str'
 

2016-12-23 12:27:37,919 - client_logger - exception : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 154, in server_added
    db_cons = self.client_connection_pool(company, company_id)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 121, in client_connection_pool
    pool_name=le_id + "con_pool",
TypeError: unsupported operand type(s) for +: 'int' and 'str'
 

2016-12-23 12:27:37,919 - client_logger - clientmain.py-server-added : unsupported operand type(s) for +: 'int' and 'str' 

2016-12-23 12:27:37,919 - client_logger - clientmain.py-server-added : cannot concatenate 'str' and 'dict' objects 

2016-12-23 12:27:37,919 - client_logger - clientmain.py-server-added : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 174, in server_added
    logger.logClientApi("Client database not available to connect ", str(company_id) + "-" + company.to_structure())
TypeError: cannot concatenate 'str' and 'dict' objects
 

2016-12-23 12:27:58,646 - client_logger - exception : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 154, in server_added
    db_cons = self.client_connection_pool(company, company_id)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 121, in client_connection_pool
    pool_name=le_id + "con_pool",
TypeError: unsupported operand type(s) for +: 'int' and 'str'
 

2016-12-23 12:27:58,646 - client_logger - clientmain.py-server-added : unsupported operand type(s) for +: 'int' and 'str' 

2016-12-23 12:28:17,374 - client_logger - exception : Traceback (most recent call last):
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 154, in server_added
    db_cons = self.client_connection_pool(company, company_id)
  File "/home/ushadevi/Usha/Python/workspace/Compliance-Mirror/Client-src-server/server/clientmain.py", line 127, in client_connection_pool
    host=data.db_ip_ip_address,
AttributeError: 'Company' object has no attribute 'db_ip_ip_address'
 

2016-12-23 12:28:17,374 - client_logger - clientmain.py-server-added : 'Company' object has no attribute 'db_ip_ip_address' 

